spring.application.name=expense-manager

spring.datasource.url=jdbc:mysql://localhost:3306/expenseTracker
spring.datasource.username=root
spring.datasource.password=242600

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true